### ISSUE TITLE
version 0.3.9 no longer silently ignores unknown block names

### ISSUE THREAD

**Issue by hn3000** [digisfera/useref#34]
Hi,

useref 0.3.9 breaks my gulp build, because unknown block names are no longer silently ignored.

I think it should either be called 1.0.0 or simply issue a warning that no handler for the custom block type was found.

**Comment by manuelcabral** [comment]
I see. Would having this behavior as an option fix the problem?

**Comment by hn3000** [comment]
Since it was upgraded automatically (it's used by gulp-useref), the warning would have to be switched on by default.

I assume my use of console.log is not appropriate for your project, but this is what wanted: https://github.com/hn3000/useref/commit/65e996e2dc0a09b3358dec57162bd6e6d695e7f5

**Comment by manuelcabral** [comment]
Ok, should be fixed on 0.3.10.

**Comment by hn3000** [comment]
yup, it's fixed

thanks!
